name: Test or PR

on: 
  pull_request:
    branches: [main]

jobs:
  teste: 
    name: test infra on PR
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Configure Aws Credencials
      uses: aws-action/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-2

    - name: IaC Apply
      env:
        COMMAND_IAC: terraform
      run: |
        cd Infrastructure
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan



